arch:
  - amd64
  - arm64
language: julia
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  - os: windows
notifications:
  email: false
os:
  - linux
  - osx
  - windows
dist: bionic
services:
  - xvfb
